---
# Create file called secrets.yml based on this file
development:
  GH_CLIENT_ID: <Github OAuth client id for this application>
  GH_CLIENT_SECRET: <Github OAuth client secret for this application>
  SESSION_SECRET: 2ygr450x/bOhvAf5BKM8b9Absn3jBXdoDixYjrUeUFzOe4kqQ5liPAE2LRinQpDmwZkl4bTP4qA9Y3RLRdCt0w==
